resources:
  containers:
  - container: linux
    image: jaci/azure-native-linux:2018.12.06
  - container: wpilib2019
    image: wpilib/roborio-cross-ubuntu:2019-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:18.04

jobs:
- job: windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-roborio'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-roborio'

- job: linux
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: linux
  steps:
  - script: sudo apt-get install -y libusb-1.0-0-dev
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-roborio'

- job: roborio
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: wpilib2019
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-desktop -xcheck -x:vision:build'

- job: pi_vision
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: raspbian
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean :vision:build'
      options: '-Pno-roborio -Pno-desktop -xcheck'

- job: tinkerboard_vision
  pool:
    vmImage: 'Ubuntu-16.04'
  container: linux
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: ':vision:installTinkerboardToolchain'
      options: '-Pno-roborio -Pno-desktop --scan --stacktrace'
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean :vision:build'
      options: '-Pno-roborio -Pno-desktop -xcheck'

- job: doxygen
  pool:
    vmImage: 'Ubuntu-16.04'
  container: linux
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'doxygen'
      options: '-Pno-roborio'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'doxygen'
      pathtoPublish: build/docs/doxygen/html